export const SOCKET_EVENTS = {
  CONNECTION: 'connection',
  // GREETING: 'greeting',
  // MESSAGE_DELIVERED: 'message:delivered',
  // MESSAGE_SEEN: 'message:seen',
  DISCONNECT: 'disconnect',
  // JOIN_ROOM: 'room:join',
  MESSAGE_SEND: 'message:send',
  MESSAGE_NEW: 'message:new',
  MESSAGE_READ: 'message:read',
  MESSAGE_SEEN: 'message:seen',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  USER_TYPING: 'user:typing',
  USER_ONLINE: 'user:online',
  USER_SEEN: 'user:seen',
  CONVERSATION_JOIN: 'conversation:join',
} as const;
