export const SOCKET_EVENTS = {
  CONNECTION: 'connection',
  // GREETING: 'greeting',
  // MESSAGE_DELIVERED: 'message:delivered',
  GET_USER_STATUS: 'user:get-status',
  DISCONNECT: 'disconnect',
  JOIN_ROOM: 'room:join',
  MESSAGE_SEND: 'message:send',
  MESSAGE_NEW: 'message:new',
  MESSAGE_READ: 'message:read',
  MESSAGE_SEEN: 'message:seen',
  MESSAGE_REACTION: 'message:reaction',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  USER_TYPING: 'user:typing',
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  USER_SEEN: 'user:seen',
  CONVERSATION_JOIN: 'conversation:join',
  STORY_PUBLISH: 'story:publish',
  STORY_NEW: 'story:new',
  STORY_READ: 'story:read',
  STORY_REACTION: 'story:reaction',
} as const;
