import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
// import { CallProvider } from '@/components/call/call-provider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import SessionProvider from '@/components/providers/SessionProvider';
import SWRegister from '@/components/layout/ServiceWorkerRegister';
import { checkServerAuth } from '@/lib/auth/check-server-auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session } = await checkServerAuth();

  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <head>
        <link
          rel="manifest"
          href="/manifest.json"
        />
        <meta
          name="theme-color"
          content="#0f172a"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider initialSession={session}>
            {/* <CallProvider> */}
            {children}
            <Toaster position="bottom-right" />
            <SWRegister />
            {/* </CallProvider> */}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
